### ISSUE TITLE
Moving to @cliqz/adblocker-puppeteer

### ISSUE THREAD

**Issue by remusao** [EU-EDPS/website-evidence-collector#1]
Hi there,

I noticed that you were using `@cliqz/adblocker` in this project, that's awesome! Regarding this comment in particular: https://github.com/EU-EDPS/website-evidence-collector/blob/1ab3829a0535c0b02f23ea8a3f097d678e254e9a/lib/setup-beacon-recording.js#L20

There is now a much nicer abstraction for puppeteer in the sub-package: [@cliqz/adblocker-puppeteer](https://github.com/cliqz-oss/adblocker/tree/master/packages/adblocker-puppeteer), it might allow you to simplify the integration quite a bit.

Let me know if I can help,

Best,
Rémi

**Comment by rriemann-eu** [comment]
Hey Rémi,

Thank you for reaching out. I'm on leave currently and can have a look only in October. I would be very happy to find then a pull request with a refractor proposal. Simpler is always better!

Have a nice day!
Robert

On 26 Sep 2019 10:43, Rémi <notifications@github.com> wrote:

Hi there,

I noticed that you were using @cliqz/adblocker in this project, that's awesome! Regarding this comment in particular: https://github.com/EU-EDPS/website-evidence-collector/blob/1ab3829a0535c0b02f23ea8a3f097d678e254e9a/lib/setup-beacon-recording.js#L20

There is now a much nicer abstraction for puppeteer in the sub-package: @cliqz/adblocker-puppeteer<https://github.com/cliqz-oss/adblocker/tree/master/packages/adblocker-puppeteer>, it might allow you to simplify the integration quite a bit.

Let me know if I can help,

Best,
Rémi

**Comment by rriemann-eu** [comment]
Thank you @remusao for your input. I like the new integration of adblocking much more.
