### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by mathiaszealid** [EU-EDPS/website-evidence-collector#102]
I'm trying to do a clean install on Ubuntu 22.04 using:
`npm install --global https://github.com/EU-EDPS/website-evidence-collector/tarball/latest`
and all I get is:
```
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm ERR! code 1
npm ERR! path /home/wec/.npm-packages/lib/node_modules/website-evidence-collector/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.mjs
npm ERR! file:///home/wec/.npm-packages/lib/node_modules/website-evidence-collector/node_modules/puppeteer/install.mjs:31
npm ERR!   const {downloadBrowser} = await importInstaller();
npm ERR!                             ^^^^^
npm ERR! 
npm ERR! SyntaxError: Unexpected reserved word
npm ERR!     at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
npm ERR!     at async link (internal/modules/esm/module_job.js:42:21)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/wec/.npm/_logs/2024-01-29T11_56_38_985Z-debug-0.log
```
I have tried both the latest master branch and the stable, as well as installing with the tarball downloaded from the EU website. Same result with each method.

[2024-01-29T11_56_38_985Z-debug-0.log](https://github.com/EU-EDPS/website-evidence-collector/files/14083935/2024-01-29T11_56_38_985Z-debug-0.log)

**Comment by rriemann** [comment]
You use node version 12. I use node version 21. Can you please install with a recent node version? See also:

https://github.com/EU-EDPS/website-evidence-collector/blob/master/CHANGELOG.md#211--2023-09-20

**Comment by mathiaszealid** [comment]
Thank you, I will try that!

**Comment by mathiaszealid** [comment]
That did the trick. Additionally I had to install some extra libraries to get it going in a headless environment. This help someone, as installing them one by one was a little tedious. 

`apt install libatk1.0-0 libatk-bridge2.0-0 libcups2 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr libxrandr2 libgbm1 libpango-1.0-0 libasound2`
