### ISSUE TITLE
Error undefined ls-remote

### ISSUE THREAD

**Issue by gitT250** [EU-EDPS/website-evidence-collector#12]
Hi,
when executing the command "npm install --global https://github.com/EU-EDPS/website-evidence-collector/tarball/latest"

I get the following error: 
undefined ls-remote -h -t ssh://git@github.com/rriemann/puppeteer -har.git
No git binary found in $path
Failed using gut.

node version 8.16.2
ubuntu 19.x

thanks

**Comment by rriemann-eu** [comment]
Can you please test if the unreleased testing version works for you?

```
npm install --global https://github.com/EU-EDPS/website-evidence-collector/tarball/master
```

**Comment by gitT250** [comment]
thanks for the link
it came to the following error

usr/local/bin/website-evidence-collector -> /usr/local/lib/node_modules/website-evidence-collector/website-evidence-collector.js

> puppeteer@1.20.0 install /usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r686378! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/.local-chromium'
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/install.js:64:16)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/.local-chromium' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.20.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@1.20.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by rriemann-eu** [comment]
This issue is unrelated to the previous one and addressed in the FAQ.

https://github.com/EU-EDPS/website-evidence-collector/blob/master/FAQ.md#why-does-the-installation-with-npm-install-fail-with-permision-denied
