### ISSUE TITLE
puppeteer problem on ubuntu

### ISSUE THREAD

**Issue by Datajuristes** [EU-EDPS/website-evidence-collector#2]
Hello,

I'm using ubuntu 16.04 32bits with chromium and the latest version of nodejs. 

When I try to do "website-evidence-collector https//mywebsite.com/" I get the two following errors  :
`(node:24893) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
/home/myself/Desktop/myfolder/testwec/pyenv/wecapp/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome: 1: /home/myself/Desktop/myfolder/testwec/pyenv/wecapp/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome: Syntax error: Unterminated quoted string

(node:24893) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24893) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

I took a look at puppeteer doc about troubleshooting on Ubuntu, so I did the command 
`ldd chrome | grep not` 
to see the eventual dependencies that might be missing. But none is detected. 

What can I do to fix this problem ? 

Thank in advance for your help.

Best regards
Xavier

**Comment by rriemann-eu** [comment]
Please try to install the Chromium browser using your Ubuntu package manager. This may help to resolve missing dependencies on which Chromium depends, which is bundled with the puppeteer library used by the website evidence collector.

```
sudo apt install -y chromium-browser
```

On 02 Oct 2019 22:01, Datajuristes <notifications@github.com> wrote:

Hello,

I'm using ubuntu 16.04 32bits with chromium and the latest version of nodejs.

When I try to do "website-evidence-collector https//mywebsite.com/" I get the two following errors :
`(node:24893) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
/home/myself/Desktop/myfolder/testwec/pyenv/wecapp/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome: 1: /home/myself/Desktop/myfolder/testwec/pyenv/wecapp/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome: Syntax error: Unterminated quoted string

(node:24893) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24893) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

I took a look at puppeteer doc about troubleshooting on Ubuntu, so I did the command
ldd chrome | grep not
to see the eventual dependencies that might be missing. But none is detected.

What can I do to fix this problem ?

Thank in advance for your help.

Best regards
Xavier

**Comment by thiru112** [comment]
@Datajuristes 
 I have this problem 
`(node:15703) UnhandledPromiseRejectionWarning: Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
    at Launcher.launch (/usr/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/Launcher.js:119:15)
    at module.exports.launch (/usr/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/Puppeteer.js:37:27)
    at /usr/lib/node_modules/website-evidence-collector/website-evidence-collector.js:59:35
    at Object.<anonymous> (/usr/lib/node_modules/website-evidence-collector/website-evidence-collector.js:405:3)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11
(node:15703) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:15703) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

@rriemann-eu 

I tried the above solution too. It did'nt work for me

**Comment by rriemann-eu** [comment]
I don't know this problem. It seems the library puppeteer is not working.

Have you considered to test any other program with puppeteer, e.g. a short code snippet from the puppeteer documentation?

**Comment by bitnesswise** [comment]
I have tried this with several Red Hat and Debian installations (including different versions of Ubuntu and Mint) and **all** of them failed with this error. Unfortunately, none of the solutions provided here or elsewhere on the internet worked.
I was able to solve it however:

* open `/etc/environment` en add `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true` (this will make the installation of wec skip the installation of puppeteer; you can remove this value after the installation has finished)
* install website evidence collector (p.e. `npm install --global https://github.com/EU-EDPS/website-evidence-collector/tarball/latest`)
* install puppeteer manually : `npm install puppeteer@1.20.0`. It needs to be that version, otherwise wec will complain later on about not being able to find the correct revision of chrome.
* at this point you have wec installed and puppeteer under your local user (unfortunately --global doesn't work for puppeteer). Because this won't work together you need to manually copy those puppeteer files to the correct paths in order for wec to be able to use it:
* `sudo cp -r node_modules/puppeteer /usr/lib/node_modules/`
* `sudo cp -r node_modules/puppeteer/.local-chromium /usr/lib/node_modules/website-evidence-collector/node_modules/puppeteer/`

**Comment by rriemann** [comment]
Thank you @bitnesswise for your analysis. I'll try a Debian based Installation myself. Have you considered to skip the installation of the bundled Chromium and employ then `PUPPETEER_EXECUTABLE_PATH` to use the system Chromium installed with `apt`?

**Comment by koenr** [comment]
I have the same problem as bitnesswise but didn't manage to install with his guidelines.
I don't have a folder  ~/node_modules/puppeteer/.local-chromium. I have installed chromium through the Ubuntu package manager (18.04)

**Comment by pythdasch** [comment]
Same problem on MacOs X 10.15.3 
when installing through terminal : sudo npm install --global https://github.com/EU-EDPS/website-evidence-collector/tarball/master

```
> puppeteer@2.1.1 install /usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r722234! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/.local-chromium'
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/install.js:66:16)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path:
   '/usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/.local-chromium' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@2.1.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@2.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/davidscheck/.npm/_logs/2020-02-24T14_40_00_576Z-debug.log
MacBook-Pro-de-david:temp davidscheck$ export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
MacBook-Pro-de-david:temp davidscheck$ sudo npm install --global https://github.com/EU-EDPS/website-evidence-collector/tarball/master
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
/usr/local/bin/website-evidence-collector -> /usr/local/lib/node_modules/website-evidence-collector/website-evidence-collector.js
/usr/local/bin/website-evidence-reporter -> /usr/local/lib/node_modules/website-evidence-collector/website-evidence-reporter.js```

**Comment by rriemann-eu** [comment]
The latest master version also supports an installation via Dockerfile. There is no documentation yet appart from two comments in the Dockerfile itself. Hence, knowing Docker basics is currently a precondition.

Then, the website evidence collector does also support the installation via yarn version < 2.0 as non-root user with:

    yarn global add https://github.com/EU-EDPS/website-evidence-collector/tarball/master --prefix $HOME

This installs the relevant website evidence collector scripts to `$HOME/bin`

**Note:** The most recent version of yarn (2.x) dropped the support of this use of global and does therefore not support this installation method.

Given the feedback on Github, I have the impression that only exceptionally puppeteer supports the installation as root user. Experience shows (and good security practice, too) that a non-root user install is recommendable.

@pythdasch: We recently installed WEC on MacOS without the need of `sudo`. Please try with yarn (version <2.0) or follow [this advice from the FAQ](https://github.com/EU-EDPS/website-evidence-collector/blob/master/FAQ.md#how-can-i-install-the-website-evidence-collector-if-i-do-not-have-rootadministrator-permission-or-do-not-want-to-employ-rootadministrator-permission).

**Comment by pythdasch** [comment]
@rriemann Thanks for your answer. I got it work but now I've to install it through docker. :p 

I'll create a new ticket for my questions.

thanks for your work :)
