### ISSUE TITLE
deprecated core-js@2.6.11

### ISSUE THREAD

**Issue by iusondemand** [EU-EDPS/website-evidence-collector#20]
This is my error log: I've tried on different new fresh lubuntu installations. I need a detailed installation "how to".

xxx~/Scaricati$ node -v
v8.11.4
xxx:~/Scaricati$ npm -v
5.8.0
~/Scaricati$ uname -r
4.18.0-25-generic
~/Scaricati$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.10
Release:        18.10
Codename:       cosmic

no root installation:

npm install --global https://github.com/EU-EDPS/website-evidence-collector/tarball/latest
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN checkPermissions Missing write access to /usr/local/lib
npm ERR! path /usr/local/lib
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib'
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/usr/local/lib\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

installation as root:

root@ xxx /Scaricati# npm install --global https://github.com/EU-EDPS/website-evidence-collector/tarball/latest
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
/root/.npm-global/bin/website-evidence-collector -> /root/.npm-global/lib/node_modules/website-evidence-collector/website-evidence-collector.js
/root/.npm-global/bin/website-evidence-reporter -> /root/.npm-global/lib/node_modules/website-evidence-collector/website-evidence-reporter.js

> puppeteer@2.0.0 install /root/.npm-global/lib/node_modules/website-evidence-collector/node_modules/puppeteer
> node install.js

module.js:549
    throw err;
    ^

Error: Cannot find module '/root/.npm-global/lib/node_modules/website-evidence-collector/node_modules/puppeteer/install.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@2.0.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by rriemann-eu** [comment]
Dear @iusondemand ,

The depreciation message on core-js is just a warning and does not impact the functionality. This is a bug of a dependency, which is tracked here: https://github.com/pugjs/pug/issues/3205

Please check the FAQ in order to understand how to install the website evidence collector without root rights: https://github.com/EU-EDPS/website-evidence-collector/blob/master/FAQ.md#why-does-the-installation-with-npm-install-fail-with-permision-denied

While some operating systems may allow to install the dependency "puppeteer" of the website evidence collector with root rights, *Ubuntu apparently does not. The bug was filed and rejected as *will not be fixed*. See: https://github.com/puppeteer/puppeteer/issues/4010

Hence, I suggest you follow the guidance in the FAQ for an installation with no root permission.

**Comment by iusondemand** [comment]
"does not impact the functionality" ... I can't install un ubuntu following the instructions. I'll try differently

**Comment by rriemann-eu** [comment]
> 
> 
> "does not impact the functionality" ... I can't install on ubuntu following the instructions. I'll try differently

The core-js warning does not impact the functionality. On our systems, the tool works well and we get the same warning. The installation error is the result of a different problem, which I explained. Follow the advice in the FAQ please for an installation with no root privileges.

**Comment by iusondemand** [comment]
Yes, it works.
Thank you
