### ISSUE TITLE
Installing with docker

### ISSUE THREAD

**Issue by pythdasch** [EU-EDPS/website-evidence-collector#30]
Hi everyone,

We use this lib in our backend and have to install all the packages to make it work.

currently I'm doing some research on hox to do it clean without having an image so big.

I'm at the state of having this error:

```
(node:45) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
2020-05-18T14:43:28.194383493Z app[web.1]: [0518/144328.184057:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
```

My dockerfile looks like that:

```
FROM ruby:2.6.3

# Set an environment variable where the app is installed to inside of Docker image:
ENV _ROOT /var/www/
ENV VOLUME_ROOT /var/www/uploads/scanner/
RUN mkdir -p $_ROOT



# Set working directory, where the commands will be ran:
WORKDIR $_ROOT

# Install dependencies
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y nodejs \
    npm

# Install latest chrome dev package and fonts to support major charsets (Chinese, Japanese, Arabic, Hebrew, Thai and a few others)
# Note: this installs the necessary libs to make the bundled version of Chromium that Puppeteer
# installs, work.
RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# Setting env up
ENV RAILS_ENV='staging'
ENV RACK_ENV='staging'

# Adding project files
COPY . $_ROOT

# Install puppeteer so it's available in the container.
RUN npm i puppeteer \
    # Add user so we don't need --no-sandbox.
    # same layer as npm install to keep re-chowned files from using up several hundred MBs more space
    && groupadd -r pptruser && useradd -r -g pptruser -G audio,video pptruser \
    && mkdir -p /home/pptruser/Downloads \
    && chown -R pptruser:pptruser /home/pptruser \
    && chown -R pptruser:pptruser /var/www/node_modules

RUN gem install bundler:2.1.4 && bundle install && npm install
RUN mkdir -p VOLUME_ROOT

USER pptruser

EXPOSE 5000
# Add a script to be executed every time the container starts.

CMD bundle exec rackup -p 5000
```

But I can't use this user, as this dockerfile is also used by the app and has to be run with root.

So I'm trying to figure out if I could isolate all this setups in an image, as you do in your dockerfile and then link it to my installation.

I'm still searching the way to do, so if you have suggestions, would be nice.

I posted here this question / answer because I think it could help people with docker.

**Comment by rriemann-eu** [comment]
Thank you for considering our software. Please note that your setup exceeds of what can be officially supported by this project. Though this issue may indeed be relevant for other users, so I keep it open for discussion.

To run chromium in docker is not easy, but there are many examples floating in the Internet. You may consider to install WEC in the Docker container of your own product and connect it to chromium running in a different Docker container. This should be possible with:

- https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#puppeteerconnectoptions (`browserURL`)
- https://github.com/browserless/chrome#puppeteer

On a first look, it seems that WEC would need to be patched to allow the configuration with `browserURL`.

**Comment by pythdasch** [comment]
so to finish, I installed it with this docker and launch the script with --no-sandbox. All working fine.

thanks :)
