### ISSUE TITLE
Error message while executing WEC

### ISSUE THREAD

**Issue by gh-giant** [EU-EDPS/website-evidence-collector#37]
Hi there,
I am new on GitHub and I am also new to running linux and programs but I managed to install Website Evidence Collector.

When I run WEC I get some error messages on some websites and I have no glue what I am doing wring. Could you please help me?

Ubuntu 20.04.0 LTS on a Synology Virtual Maschine Manager

```
website-evidence-collector  https://datenschutz-opitz.de -q -j -t 20201029 datenschutz-opitz.de --overwrite -- --lang "de" --ignore-certificate-errors
(node:173850) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: form.action.startsWith is not a function
    at __puppeteer_evaluation_script__:9:26
    at Array.filter (<anonymous>)
    at __puppeteer_evaluation_script__:8:8
    at ExecutionContext._evaluateInternal (/home/ggopitz/.npm-packages/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/home/ggopitz/.npm-packages/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.evaluate (/home/ggopitz/.npm-packages/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/DOMWorld.js:112:20)
  -- ASYNC --
    at Frame.<anonymous> (/home/ggopitz/.npm-packages/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.evaluate (/home/ggopitz/.npm-packages/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/Page.js:860:43)
    at Page.<anonymous> (/home/ggopitz/.npm-packages/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/helper.js:112:23)
    at /home/ggopitz/.npm-packages/lib/node_modules/website-evidence-collector/website-evidence-collector.js:275:35
(node:173850) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:173850) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by rriemann-eu** [comment]
Dear user,

thank you for your interest in WEC. I copy'n'pasted your command and executed it on my Linux opensuse computer with no error message using the testing version (master/HEAD) of WEC.

Can you please explain which version you have installed or how you have installed the WEC. Indeed, many fixes and few features are only in the testing (master/HEAD) version.

Changes in the testing version: https://github.com/EU-EDPS/website-evidence-collector/blob/master/CHANGELOG.md#head

Installation of the testing version is explained in https://github.com/EU-EDPS/website-evidence-collector/blob/master/README.md#installation , in short:

     npm install --global https://github.com/EU-EDPS/website-evidence-collector/tarball/master

**Comment by gh-giant** [comment]
Hi rriemann-eu,

I installed the latest version (0.4.0) with
` npm install --global https://github.com/EU-EDPS/website-evidence-collector/tarball/latest`

I've done the following (as far as I can remember):

```
sudo apt install npm
sudo apt install nodejs
npm install --global https://github.com/EU-EDPS/website-evidence-collector/tarball/latest
mkdir "${HOME}/.npm-packages"
npm config set prefix "${HOME}/.npm-packages"
NPM_PACKAGES="${HOME}/.npm-packages"
export PATH="$PATH:$NPM_PACKAGES/bin"
export MANPATH="${MANPATH-$(manpath)}:NPM_PACKAGES/share/man"
```
Does the help?

**Comment by rriemann-eu** [comment]
Please install then the testing version instead of the latest release version and try again.

**Comment by gh-giant** [comment]
That really solved the problem. I was only confused by tha phrase "... to get a potentially broken testing version, which includes the latest changes." I didn't want to have a potentially broken version. Therefore, I used the latest version.
Thanks für helping and for the great tool.
