### ISSUE TITLE
How to reference --html-template?

### ISSUE THREAD

**Issue by gh-giant** [EU-EDPS/website-evidence-collector#38]
Hi folks,
in `website-evidence-collector --help` there is a flag called `--html-template`.

Can you tell me how I can reference to a custom pug-template and where I have to locate it so WEG is loading my custom template?

The original template.pug is located in `./assets`. When I copy that one I make some changes like I want to have my template to to look like, I call it with `--html-template "./path/to/changed_template.pug"` but it doesn't change anything.

Where is my mistake?

**Comment by mercaderd** [comment]
It is not your mistake. I detected the same issue and created a pull request. While approved and merged you could try using '--html_template' instead of '--html-template' as a temporary workaround.

**Comment by rriemann-eu** [comment]
Thank you for reporting and fixing! I just updated the master branch. Please install the testing version according to our README to take advantage of this recent change.
