### ISSUE TITLE
Video guide is missing two characters from line ends

### ISSUE THREAD

**Issue by exasperatedof** [EU-EDPS/website-evidence-collector#4]
I think you need to widen the screen for capture by two character widths, eg "--out 
t" should have been "--output" wrapped.

**Comment by rriemann-eu** [comment]
There is a trade-of to make between character size for readability and wrapping of long lines. The video is just meant to give a short impression of the tool in action.

The readme accurately spells out that the option must be `--out`. Therefore, this issue is not given priority anytime soon.

**Comment by exasperatedof** [comment]
This seems to be just a presentation problem on the EDPS site (https://edps.europa.eu/press-publications/edps-inspection-software_en).

I can see the animation from screencast-call.svg fine on github, and by View Image Info from the website too. Perhaps the overall Europa style sheets are truncating the viewport?
![Screenshot_20191003_123724](https://user-images.githubusercontent.com/56116296/66123806-c4dd9d00-e5da-11e9-9204-123e9fe1b8f1.png)

**Comment by rriemann-eu** [comment]
I understand now better what you mean. I will inform the website team. This is not an issue that can be fixed within the software here.

**Comment by exasperatedof** [comment]
You're a real optimist thinking people with both look at a picture and read the readme! ;-)
