### ISSUE TITLE
Download link 404

### ISSUE THREAD

**Issue by vincentcox** [EU-EDPS/website-evidence-collector#41]
Steps to reproduce and the links:

![image](https://user-images.githubusercontent.com/9286611/99674446-57a6f880-2a76-11eb-8e41-09eb14d1c818.png)

Link: https://edps.europa.eu/press-publications/edps-inspection-software_en

![image](https://user-images.githubusercontent.com/9286611/99674484-65f51480-2a76-11eb-89d5-261fa3808b47.png)
Link: https://joinup.ec.europa.eu/solution/website-evidence-collector/releases
![image](https://user-images.githubusercontent.com/9286611/99674503-6b525f00-2a76-11eb-8bfe-b1ecd5b8592d.png)

Proposed fix: check internally where it is moved to or what went wrong.

**Comment by rriemann-eu** [comment]
Thanks for pointing out this problem. I forward it to the responsible team.

The versions on joinup should be in sync with the tagged released versions on Github.
https://joinup.ec.europa.eu/collection/free-and-open-source-software/solution/website-evidence-collector

**Comment by rriemann-eu** [comment]
The link on the EDPS  website has been fixed.
