### ISSUE TITLE
Dashboard for multiple websites

### ISSUE THREAD

**Issue by vincentcox** [EU-EDPS/website-evidence-collector#44]
Hi there,

I created a tool to make a dashboard for multiple websites. 

![image](https://user-images.githubusercontent.com/9286611/101623329-9518f900-3a18-11eb-8372-c3e335ef1657.png)

Feel free to check this out and give feedback.

Link: https://github.com/vincentcox/privacy-dashboard

**Comment by rriemann-eu** [comment]
This looks awesome. We will have a closer look next year and will consider recommending it to the EU institutions for their compliance work.

I could not see it in the images: Can you consider to include a "powered by EDPS Website Evidence Collector" at the very bottom of the dashboard – possibly using the logo? While I have not checked yet if the license requires this, it would help people living in the EU to recognise free software projects supported by their taxes. :slightly_smiling_face: :eu: .

**Comment by vincentcox** [comment]
Thanks for the initial feedback already!

I share this idea and it's already included with a notice (and link) at the end of the dashboard:

![image](https://user-images.githubusercontent.com/9286611/101629838-3c4e5e00-3a22-11eb-83fd-09b7efc3cfab.png)

But this was indeed not visible in the other screenshots. 

If you would like another notice or a more clear one, feel free to give suggestions!
