### ISSUE TITLE
UnhandledPromiseRejectionWarning: TimeoutError: 

### ISSUE THREAD

**Issue by info247** [EU-EDPS/website-evidence-collector#46]
I have installed the software on a Windows system. After running the command:

website-evidence-collector --output output/example.com --overwrite https://example.com

I get this error message:

(node:17384) UnhandledPromiseRejectionWarning: TimeoutError: waiting for target failed: timeout 30000ms exceeded
    at Function.waitWithTimeout (C:\Users\Office\AppData\Roaming\npm\node_modules\website-evidence-collector\node_modules\puppeteer\lib\helper.js:228:26)
    at Browser.waitForTarget (C:\Users\Office\AppData\Roaming\npm\node_modules\website-evidence-collector\node_modules\puppeteer\lib\Browser.js:214:27)
    at Browser.<anonymous> (C:\Users\Office\AppData\Roaming\npm\node_modules\website-evidence-collector\node_modules\puppeteer\lib\helper.js:112:23)
    at ChromeLauncher.launch (C:\Users\Office\AppData\Roaming\npm\node_modules\website-evidence-collector\node_modules\puppeteer\lib\Launcher.js:247:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async C:\Users\Office\AppData\Roaming\npm\node_modules\website-evidence-collector\website-evidence-collector.js:74:19
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17384) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17384) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Any suggestion to resolve this?

**Comment by andretunes** [comment]
Hello! To try help you out, what domain did you used?

**Comment by info247** [comment]
Hello Andre

 

Thank you very much.

 

I used oldmutual.com.

 

Kind regards … Peter

**Comment by andretunes** [comment]
Hello again,

I was not able to reproduce the error, can I check it though Anydesk or something else?

Kind regards,
André

**Comment by info247** [comment]
Hello Andre

 

I appreciate your willingness to assist.

 

Can we set up some time tomorrow or Wednesday for you to check?

Please let me know what time is best for you.

 

Kind regards … Peter

**Comment by andretunes** [comment]
Hello!

Tomorrow is great for me, you can email me at the hour that is best for you with the ID of Anydesk (the email is in my profile).

Kind regards!

**Comment by info247** [comment]
Hello Andre

 

Thank you. Will do.

 

Regards … Peter

**Comment by andretunes** [comment]
If anything occurs meanwhile, just let me know.

Kind regards,
André

**Comment by info247** [comment]
Hello Andre

 

I am available for the next 2 hours today.

 

This is my AnyDesk session ID; 825654967.

 

The website-evidence-collector is installed on my laptop under both Windows and Debian.

 

The Windows implementation produces the results without output.

 

The Debian implementation (about which I have a basic understanding) has a command not found error.

 

Kind regards

Peter Hill

**Comment by danielvonwi** [comment]
FYI – your convo is being distributed to all subscribers of the github project.
Good advice not to share personal details like AnyDesk ID’s ,)

Best, Daniel

Von: info247 <notifications@github.com>
Antworten an: EU-EDPS/website-evidence-collector <reply@reply.github.com>
Datum: Dienstag, 19. Januar 2021 um 14:35
An: EU-EDPS/website-evidence-collector <website-evidence-collector@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [EU-EDPS/website-evidence-collector] UnhandledPromiseRejectionWarning: TimeoutError: (#46)

Hello Andre



I am available for the next 2 hours today.



This is my AnyDesk session ID; 825654967.



The website-evidence-collector is installed on my laptop under both Windows and Debian.



The Windows implementation produces the results without output.



The Debian implementation (about which I have a basic understanding) has a command not found error.



Kind regards

Peter Hill

**Comment by andretunes** [comment]
Hello!

Asked the connection, sir!
