### ISSUE TITLE
0.3.0 fails to install in openSUSE 15.1

### ISSUE THREAD

**Issue by exasperatedof** [EU-EDPS/website-evidence-collector#5]
Tested in clean VM with under virtualbox. Current with all patches (zypper ref; zypper up). Same behaviour seen with both the official 0.3 tarball and pointing to the latest, output below:

linux-702v:~# zypper in nodejs10 git

linux-702v:~ # npm install --global https://github.com/EU-EDPS/website-evidence-collector/tarball/latest             
/usr/local/bin/website-evidence-collector -> /usr/local/lib/node_modules/website-evidence-collector/website-evidence-collector.js

> puppeteer@1.20.0 install /usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r686378! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/.local-chromium'
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/install.js:64:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path:
   '/usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/.local-chromium' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.20.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@1.20.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-03T10_56_24_942Z-debug.log

The paths under /usr/local/lib.... seem to be deleted during some of the previous package installation steps. Digging into the complete log, it seems the puppeteer install is failing:

3313 silly install puppeteer@1.20.0
3314 info lifecycle puppeteer@1.20.0~install: puppeteer@1.20.0
3315 verbose lifecycle puppeteer@1.20.0~install: unsafe-perm in lifecycle false
3316 verbose lifecycle puppeteer@1.20.0~install: PATH: /usr/lib64/node_modules/npm10/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/node_modules/.bin:/usr/local/lib/node_modules/website-evidence-collector/node_modules/.bin:/usr/local/lib/node_modules/.bin:/sbin:/usr/sbin:/usr/local/sbin:/root/bin:/usr/local/bin:/usr/bin:/bin
3317 verbose lifecycle puppeteer@1.20.0~install: CWD: /usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer
3318 silly lifecycle puppeteer@1.20.0~install: Args: [ '-c', 'node install.js' ]
3319 silly lifecycle puppeteer@1.20.0~install: Returned: code: 1  signal: null
3320 info lifecycle puppeteer@1.20.0~install: Failed to exec install script
3321 timing action:install Completed in 322ms
3322 verbose unlock done using /root/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
3323 timing stage:rollbackFailedOptional Completed in 527ms
3324 timing stage:runTopLevelLifecycles Completed in 8646ms
3325 verbose stack Error: puppeteer@1.20.0 install: `node install.js`
3325 verbose stack Exit status 1
3325 verbose stack     at EventEmitter.<anonymous> (/usr/lib64/node_modules/npm10/node_modules/npm-lifecycle/index.js:301:16)
3325 verbose stack     at EventEmitter.emit (events.js:198:13)
3325 verbose stack     at ChildProcess.<anonymous> (/usr/lib64/node_modules/npm10/node_modules/npm-lifecycle/lib/spawn.js:55:14)
3325 verbose stack     at ChildProcess.emit (events.js:198:13)
3325 verbose stack     at maybeClose (internal/child_process.js:982:16)
3325 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
3326 verbose pkgid puppeteer@1.20.0
3327 verbose cwd /root
3328 verbose Linux 4.12.14-lp151.28.16-default
3329 verbose argv "/usr/bin/node10" "/usr/bin/npm-default" "install" "--global" "https://github.com/EU-EDPS/website-evidence-collector/tarball/latest"
3330 verbose node v10.16.3
3331 verbose npm  v6.9.0
3332 error code ELIFECYCLE
3333 error errno 1
3334 error puppeteer@1.20.0 install: `node install.js`
3334 error Exit status 1
3335 error Failed at the puppeteer@1.20.0 install script.
3335 error This is probably not a problem with npm. There is likely additional logging output above.
3336 verbose exit [ 1, true ]

Sorry I'm not familiar with nodejs/puppet to debug myself.

This install has been done as root. Its unclear if the tool can only then be run as root, which isn't a good idea (security) and may have display permission problems. If not, does a normal/non-superuser need to setup explicit paths after a systemwide install?

**Comment by rriemann-eu** [comment]
I run the tool with a user account without root permissions. For this, I follow this generic advice for all NPM-based tools.

https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md

In short, before executing `npm install`, run as non-root user:

```shell
mkdir "${HOME}/.npm-packages"
npm config set prefix "${HOME}/.npm-packages"
```

To ensure that executables from NPM (such as our website-evidence-collector) can be found, add the following to your .bashrc/.zshrc:

```shell
NPM_PACKAGES="${HOME}/.npm-packages"

export PATH="$PATH:$NPM_PACKAGES/bin"

# Preserve MANPATH if you already defined it somewhere in your config.
# Otherwise, fall back to `manpath` so we can inherit from `/etc/manpath`.
export MANPATH="${MANPATH-$(manpath)}:$NPM_PACKAGES/share/man"
```

I agree that a new section on NPM configuration should be added to the README. I'm happily accepting pull requests.

**Comment by exasperatedof** [comment]
Thanks. That fixed it straight-away.
