### ISSUE TITLE
Option --headless has no effect

### ISSUE THREAD

**Issue by noleakseu** [EU-EDPS/website-evidence-collector#50]
WEC executes Chrome in headless mode submitting `--headless=false` or `--headless false`.

**Comment by rriemann-eu** [comment]
Please try `--no-headless`. I rely on a library to implement the option parsing: https://github.com/yargs/yargs/blob/master/docs/tricks.md#negating-boolean-arguments

Please reopen if this does not help you.

**Comment by noleakseu** [comment]
Yes, `--no-headless` is right one, thank you. I found a misinformational argument `[boolean] [default: true]` in the help:
`--headless             Hides the browser window      [boolean] [default: true]`
