### ISSUE TITLE
Feature Request: Improve Reporting Output

### ISSUE THREAD

**Issue by Synchro** [EU-EDPS/website-evidence-collector#6]
While I can see that WEC does its job in collecting data, it's not clear how you're meant to view the output - raw JSON isn't very people-friendly. Are there any suggested tools for viewing the results?

For example, the very similar analyser at https://webbkoll.dataskydd.net/ does pretty much the same checks, but has very clear, readable output too. I'm imagining some tool that takes the output from WEC and renders a similar kind of report, as HTML, PDF, Excel or whatever. Ideas?

**Comment by rriemann-eu** [comment]
The EDPS exports output to yaml which is more people friendly than json.

Then, we use pandoc, ruby, xelatex, continuous integration tools on top of git, and custom templates to generate PDF files.

**Comment by Synchro** [comment]
From the run I just did, it seems to output a mixture of JSON and yaml, with some duplication (e.g. `inspection.json` and `inspection.yml` seem to say pretty much the same thing). The site I tested has no trackers or cookies, and the yaml files generated don't look like valid yaml - they contain just `[]`, which looks more like an empty JSON array than anything yamlish.

For the reporting, that was pretty much the point of my question - if you can't make something easily viewable without having to write a bunch of custom code, it's not especially useful. Are you planning on making your reporting tools available too?

**Comment by rriemann-eu** [comment]
I did some research and think we can improve reporting. The chain of tools mentioned above is most likely to complex to install and to use for those that cannot work with the existing output.

I did some research and suggest to proceed as follows:

- use [pugjs](https://pugjs.org/api/getting-started.html) as a template engine to generate from JSONoutput html output
- include a default pug template with the tool that works for most purposes
- output next to YAML and JSON an HTML version in the output folder
- add an option `--html` to output the html file directly on the console
- add an option `--html-template=[FILE]` to specify a custom pug template to generate html files

The produced html file could in theory integrate some javascript to improve the displaying.

Also, the html file produced using the default template should support [pandoc](https://pandoc.org/) to create DOCX, ODT and PDF files. Of course, users can also open the html file in their modern browsers and generate PDFs from there.

If someone considers to work or contribute to this feature, please let us know here in advance.

**Comment by ttan** [comment]
Hi @rriemann-eu, if you still need someone to contribute on this, I'm more than happy to help!

**Comment by rriemann-eu** [comment]
Buongiorno @ttz,

grazie per la tua proposta! After approval by the hierarchy, I can extend the linked pull request with a bit more text that we have already. Once added, I would be happy to receive your contributions to further improve it. I let you you here again.

Also, I'm attending PLSC in Amsterdam tomorrow and stay until Saturday. You as well? Let me know via Twitter or Mail (`firstname.lastname AT edps.europa.eu`)

**Comment by ttan** [comment]
Great, I'll wait here for any news about it. I'll send you on email on the other matter!

**Comment by rriemann-eu** [comment]
With the last introduced changes, we have now a html output that can be open in any modern browser and printed on paper or as PDF. I close this one.

Of course, there is always something to improve. Do not hesitate to reopen this issue or create a new issue.
