### ISSUE TITLE
Trouble on Ubuntu desktop

### ISSUE THREAD

**Issue by dega69** [EU-EDPS/website-evidence-collector#67]
dear all,
I am trying to install wec on the last ubutu desktop. I installed nodejs and then npm. Nodejs is V10.19.0 npm is 6.14.4
When I try to installa wec using npm install --global https://github.com/EU-EDPS/website-evidence-collector/tarball/latest
I receive few warn about deprecated package and the error. I tried both as user or with sudo but not works
thanks for help

**Comment by rriemann-eu** [comment]
Dear @dega69,

the depreciation warnings should be not critical. Can you please tell me which error you have encountered? Ideally, you could provide the full output in text or as a screenshot.

**Comment by dega69** [comment]
here the screenshot of the installation. Thanks
![VirtualBox_ desktop_16_09_2021_09_46_51](https://user-images.githubusercontent.com/89895745/133572323-c9b23bb7-510d-4437-a180-e6de1055aa66.png)
![VirtualBox_ desktop_16_09_2021_09_47_22](https://user-images.githubusercontent.com/89895745/133572392-d5b19628-19ad-4bb3-b09a-4f7d99f1e417.png)

**Comment by dega69** [comment]
Thanke rriemann-eu here is the two screen shot of the installation:
![VirtualBox_ desktop_16_09_2021_09_46_51](https://user-images.githubusercontent.com/89895745/133572754-27611ef6-df5b-4aed-b481-a737580ef7c8.png)
![VirtualBox_ desktop_16_09_2021_09_47_22](https://user-images.githubusercontent.com/89895745/133572774-46d4486f-430d-4645-ace4-47173ab09383.png)

**Comment by rriemann-eu** [comment]
I see that the tool seeks to install into a system folder (`/usr/local`), which requires root rights.

To avoid this issue, please check this FAQ item on installation with only user permission: https://github.com/EU-EDPS/website-evidence-collector/blob/master/FAQ.md#installation-and-use
