### ISSUE TITLE
Security questions

### ISSUE THREAD

**Issue by ZikBurns** [EU-EDPS/website-evidence-collector#86]
Hi, I want to use this tool in my organization. For that I need to know more about its security specifications.

What kind of controls have been implemented to secure the tool?
Does the tool encrypt or sign data?
Is there any vulnerability information available?

**Comment by rriemann** [comment]
The tool can be installed in an air-gapped network and works in an isolated environment (e.g. Docker).

The output is neither signed nor encrypted. However, both can be done with other tools (such as GPG).

No vulnerability information is available.

Please read the applicable license for more information on liability: https://github.com/EU-EDPS/website-evidence-collector/blob/master/LICENSE.txt
