### ISSUE TITLE
EasyList: Detected beacons are't beacons

### ISSUE THREAD

**Issue by ZikBurns** [EU-EDPS/website-evidence-collector#87]
I am analysing my website and I find that the beacons that the tool detects aren't really beacons:
https://myURL/files/social%20media%20icons/icon-reddit.svg 
https://myURL/files/social%20media%20icons/icon-instagram.svg 
https://myURL/files/social%20media%20icons/icon-youtube.svg
https://myURL/files/social%20media%20icons/icon-linkedin.svg 
https://myURL/files/social%20media%20icons/icon-flickr.svg  
https://myURL/files/social%20media%20icons/icon-twitter.svg 
https://myURL/files/social%20media%20icons/icon-facebook.svg 
https://myURL/privacy-policy/privacy-policy.js

None of the icons detected have any script, they are just images. Could it be that these are detected just because part of the path is in [fanboy-annoyance.txt](https://easylist.to/easylist/fanboy-annoyance.txt)? And they aren't detected because of being real beacons? 

 I'm just starting to use the tool and haven't figured everything out, any help is appreciated.

**Comment by rriemann** [comment]
I confirm that when such files are loaded from a first party host, there is no additional data protection risk.

The code to identify beacons can be found here:

https://github.com/EU-EDPS/website-evidence-collector/blob/master/lib/setup-beacon-recording.js#L94

If the documentation makes the possibility of these false positives not clear enough, the documentation should be changed.

Please re-open if you have specific proposals on how WEC could be improved. You may also consider to ask fanboy annoyance to make their filter more specific.
