### ISSUE TITLE
Table width in Firefox

### ISSUE THREAD

**Issue by ulab** [EU-EDPS/website-evidence-collector#94]
Setting the table `width` to `max-content` does not not produce the correct result in Firefox 111.

<img width="525" alt="Screenshot 2023-04-23 at 21 37 43" src="https://user-images.githubusercontent.com/504616/233861255-c0e43ef8-72d0-4770-92f1-6d3c113fd8b6.png">

**Comment by rriemann** [comment]
Don't we use the CSS `width: 100%;` on tables to stretch them over the entire page?

**Comment by ulab** [comment]
`max-width: 100%;` is set, but `width: max-content;`. As soon as I disable the `width` declaration, the tables go to full width.

![image](https://user-images.githubusercontent.com/504616/234189069-45d8576d-f0d5-40b3-a508-e6c5259d038e.png)
