### ISSUE TITLE
www subdomain: first or third party mixup ?

### ISSUE THREAD

**Issue by creativeworkx** [EU-EDPS/website-evidence-collector#95]
Hello guys,

I launched the tool using this command:

`website-evidence-collector --html --overwrite --first-party-uri diepresse.com https://www.diepresse.com 2> /dev/null`

Then I open the generated report and it tells me:

> For the subsequent analysis, the following hosts (with their path) were defined as first-party:

    www.diepresse.com
    diepresse.com

Which would be the desired result.

But when I look at the cookies, I get the following result:

`www.diepresse.com =>  first-party; diepresse.com => third-party.`

Is this behavior intended?

**Comment by rriemann** [comment]
Can you please try instead:

~~~
website-evidence-collector --html --overwrite --first-party-uri http://diepresse.com https://www.diepresse.com 2> /dev/null
~~~

The URI argument expects also a schema.

**Comment by creativeworkx** [comment]
Thank you, this did the job!
