### ISSUE TITLE
Consent-Management-Tool "decision" saved in LocalStorage

### ISSUE THREAD

**Issue by Iouis39** [EU-EDPS/website-evidence-collector#96]
When I want to test the consent-management-tool, then I can simply use `--set-cookie ""`. But what if the website saves the value not as cookie but with the LocalStorage? Is there a way to use this option for the LocalStorage?

**Comment by rriemann** [comment]
Currently, there is only one way.

- You use Chrome or Chromium with a new profile
- You visit the website
- You consent to set the LocalStorage option
- you launch the website-evidence-collector with the option `--browser-profile` followed by the path to the folder of the new profile
